FROM registry.devshift.net/bayesian/bayesian-api
MAINTAINER Tomas Tomecek <ttomecek@redhat.com>

COPY . /bayesian
WORKDIR /bayesian
RUN cd tests && pip3 install -r ./requirements.txt

ENV PYTHONDONTWRITEBYTECODE=1
ENV POSTGRESQL_USER=coreapi
ENV POSTGRESQL_PASSWORD=coreapi
ENV POSTGRESQL_DATABASE=coreapi
ENV PGBOUNCER_SERVICE_HOST=coreapi-pgbouncer

RUN pip3 install -U git+https://github.com/selinon/selinon && \
 pip3 install -U git+https://github.com/selinon/selinonlib

ENTRYPOINT ["/bayesian/hack/exec_tests.sh"]
