FROM docker-registry.usersys.redhat.com/bayesian/bayesian-api
MAINTAINER Slavek Kabrda <slavek@redhat.com>

RUN pip3 install alembic

RUN mkdir -p /fabric8-analytics/fabric8-analytics-server
WORKDIR /fabric8-analytics/fabric8-analytics-server
VOLUME /fabric8-analytics

ENTRYPOINT ["bash", "-c"]
