openapi: 3.0.1
info:
  title: Analytics Core API Specs for Version 2
  version: "2"
servers:
- url: https://f8a-analytics-2445582058137.production.gw.apicast.io/api/v2
  description: "Dependency Analytics Server"
security:
- tokenAuth: []
paths:
  /component-analyses/{eco}/{name}/{ver}:
    get:
      tags:
      - Scan Services
      summary: Get security and other details about a software component and recommendations
        to change to a more secured version
      operationId: f8a_scanner.api_v2.component-analyses
      parameters:
      - name: eco
        in: path
        description: component ecosystem
        required: true
        schema:
          type: string
      - name: name
        in: path
        description: component name
        required: true
        schema:
          type: string
      - name: ver
        in: path
        description: component version
        required: true
        schema:
          type: string
      - name: security-vendor
        in: header
        description: Security Vendor
        schema:
          type: string
          enum:
          - snyk
      responses:
        200:
          description: Detailed response for the requested application component
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentAnalysesResponse'
        202:
          description: Package is currently Unavailable. Please try again later
          content: {}
        401:
          description: Request unauthorized
          content: {}
        404:
          description: Data not found
          content: {}
components:
  schemas:
    VulnerabilityDetails:
      title: Vulnerability Details
      type: object
      properties:
        vulneability:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              cvss:
                type: string
      description: Information of the vulnerability found

    PrivateRecommendation:
      title: Vendor Private Recommendation Information
      type: object
      properties:
        change_to:
          type: string
        component-analyses:
          $ref: '#/components/schemas/VulnerabilityDetails'
        message:
          type: string
        severity:
          type: string
        public_vulnerabilities:
          type: integer
        private_vulnerabilities:
          type: integer
        exploitable_vulnerabilities:
          type: integer
        vendor_package_link:
          type: string
      description: Vendor Recommendation information for Premium Recommendation.

    PublicRecommendation:
      title: Vendor Public Recommendation Information
      type: object
      properties:
        change_to:
          type: string
        component-analyses:
          $ref: '#/components/schemas/VulnerabilityDetails'
        message:
          type: string
        severity:
          type: string
        public_vulnerabilities:
          type: integer
        vendor_package_link:
          type: string
      description: Vendor Recommendation information for Standard Recommendation.

    ComponentAnalysesData:
      title: Component Analyses Data
      type: object
      properties:
        recommendation:
          type: object
          items:
            oneOf:
              - $ref: '#/components/schemas/PrivateRecommendation'
              - $ref: '#/components/schemas/PublicRecommendation'
      description: Component analyses data
    ComponentAnalysesResponse:
      title: Response of Component Analyses
      type: object
      properties:
        result:
          $ref: '#/components/schemas/ComponentAnalysesData'
      description: Component analyses response
  securitySchemes:
    tokenAuth:
      type: apiKey
      description: 3Scale Token Auth is used for Authentication
      name: user_key
      in: query
