"""Migrate to dynamic control flow

Revision ID: 02b91e918b43
Revises: b4fbc8e04c81
Create Date: 2016-10-03 13:45:08.334340

"""

# revision identifiers, used by Alembic.
revision = '02b91e918b43'
down_revision = 'b4fbc8e04c81'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_requests', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('worker_results', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'worker_results', ['worker_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_results', type_='unique')
    op.drop_column('worker_results', 'worker_id')
    op.drop_column('analysis_requests', 'parent_id')
    ### end Alembic commands ###
