"""add es marker

Revision ID: 133cd5484609
Revises: 813f9a704eb7
Create Date: 2016-07-25 15:50:01.605900

"""

# revision identifiers, used by Alembic.
revision = '133cd5484609'
down_revision = '813f9a704eb7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esmarker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_result_id'], ['worker_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esmarker')
    ### end Alembic commands ###
