"""Add external_reqeust_id to WorkerResult

Revision ID: 20cf59abbda8
Revises: 3fd95b3a69f5
Create Date: 2016-06-30 11:27:28.268412

"""

# revision identifiers, used by Alembic.
revision = '20cf59abbda8'
down_revision = '3fd95b3a69f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_results', sa.Column('external_request_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_results', 'external_request_id')
    ### end Alembic commands ###
