"""empty message

Revision ID: 22a1cd66a9c6
Revises: 963d3d929b19
Create Date: 2016-05-10 06:50:04.158499

"""

# revision identifiers, used by Alembic.
revision = '22a1cd66a9c6'
down_revision = '963d3d929b19'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('token', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('epvs', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('epv', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('batch')
    ### end Alembic commands ###
