"""introduce_stackreq_origin_flag

Revision ID: 2bd5f6d0c8b0
Revises: 76c5fd72744e
Create Date: 2016-08-29 06:38:46.883894

"""

# revision identifiers, used by Alembic.
revision = '2bd5f6d0c8b0'
down_revision = '76c5fd72744e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_analyses_request', sa.Column('origin', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stack_analyses_request', 'origin')
    ### end Alembic commands ###
