"""removing startTime and endTime

Revision ID: 3eb32f202f93
Revises: b19a6deb869d
Create Date: 2016-10-26 14:07:04.720228

"""

# revision identifiers, used by Alembic.
revision = '3eb32f202f93'
down_revision = 'b19a6deb869d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stack_analyses_request', 'endTime')
    op.drop_column('stack_analyses_request', 'startTime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_analyses_request', sa.Column('startTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('stack_analyses_request', sa.Column('endTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
