"""Relative usage.

Revision ID: 424427c5f988
Revises: 02b91e918b43
Create Date: 2016-10-05 19:10:22.428248

"""

# revision identifiers, used by Alembic.
revision = '424427c5f988'
down_revision = '02b91e918b43'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    """Upgrade the database to a newer revision."""
    # commands auto generated by Alembic - please adjust! ###
    op.add_column('component_gh_usage', sa.Column('percentile_rank', sa.Integer(), nullable=False))
    # end Alembic commands ###


def downgrade():
    """Downgrade the database to an older revision."""
    # commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_gh_usage', 'percentile_rank')
    # end Alembic commands ###
