"""stack-analyses-request

Revision ID: 47f4ce1e8d75
Revises: 20cf59abbda8
Create Date: 2016-07-20 18:17:18.757434

"""

# revision identifiers, used by Alembic.
revision = '47f4ce1e8d75'
down_revision = '20cf59abbda8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack_analyses_request',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('submitTime', sa.DateTime(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('requestJson', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stack_analyses_request')
    ### end Alembic commands ###
