"""remove_batches

Revision ID: 6e7ff4c3177e
Revises: 51cb05927271
Create Date: 2017-03-10 15:41:43.818325

"""

# revision identifiers, used by Alembic.
revision = '6e7ff4c3177e'
down_revision = '51cb05927271'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches_versions')
    op.drop_table('batch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches_versions',
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batch_token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_token'], ['batch.token'], name='batches_versions_batch_token_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name='batches_versions_version_id_fkey')
    )
    op.create_table('batch',
    sa.Column('token', sa.INTEGER(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token', name='batch_pkey')
    )
    # ### end Alembic commands ###
