"""gh usage stats

Revision ID: 76c5fd72744e
Revises: 2ff043a5af5b
Create Date: 2016-08-15 13:02:58.023929

"""

# revision identifiers, used by Alembic.
revision = '76c5fd72744e'
down_revision = '2ff043a5af5b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_gh_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('ecosystem_backend', sa.dialects.postgresql.ENUM('none', 'npm', 'maven', 'pypi', 'rubygems', 'scm', 'crates', name='ecosystem_backend_enum', create_type=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('LOCALTIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_gh_usage')
    ### end Alembic commands ###
