"""remove_analyses_column

Revision ID: 79d88d57baa7
Revises: 133cd5484609
Create Date: 2016-07-29 08:12:12.483676

"""

# revision identifiers, used by Alembic.
revision = '79d88d57baa7'
down_revision = '133cd5484609'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'analyses')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('analyses', postgresql.JSONB(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
