"""add app stack tables

Revision ID: 9d605c7725d8
Revises: 21b3add12b10
Create Date: 2016-11-01 12:28:52.002840

"""

# revision identifiers, used by Alembic.
revision = '9d605c7725d8'
down_revision = '21b3add12b10'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_json', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similar_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appstack_id', sa.Integer(), nullable=True),
    sa.Column('dependency_list', postgresql.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['appstack_id'], ['app_stacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_stacks')
    op.drop_table('app_stacks')
    ### end Alembic commands ###
