"""analytics tables

Revision ID: fc7ea2a7e386
Revises: 9d605c7725d8
Create Date: 2016-11-04 11:04:47.236626

"""

# revision identifiers, used by Alembic.
revision = 'fc7ea2a7e386'
down_revision = '9d605c7725d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_ref_stack', sa.Boolean(), nullable=False),
    sa.Column('stack_json', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('similar_stacks', sa.Column('analysis', postgresql.JSONB()))
    op.add_column('similar_stacks', sa.Column('similar_stack_id', sa.Integer(), nullable=False))
    op.add_column('similar_stacks', sa.Column('similarity_value', sa.Float(), nullable=False))
    op.add_column('similar_stacks', sa.Column('stack_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('sim_unique', 'similar_stacks', ['stack_id', 'similar_stack_id'])
    op.drop_constraint('similar_stacks_appstack_id_fkey', 'similar_stacks', type_='foreignkey')
    op.create_foreign_key(None, 'similar_stacks', 'stacks', ['stack_id'], ['id'])
    op.create_foreign_key(None, 'similar_stacks', 'stacks', ['similar_stack_id'], ['id'])
    op.drop_column('similar_stacks', 'dependency_list')
    op.drop_column('similar_stacks', 'appstack_id')
    op.drop_table('reference_stacks')
    op.drop_table('app_stacks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similar_stacks', sa.Column('appstack_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('similar_stacks', sa.Column('dependency_list', postgresql.JSONB(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'similar_stacks', type_='foreignkey')
    op.drop_constraint(None, 'similar_stacks', type_='foreignkey')
    op.create_foreign_key('similar_stacks_appstack_id_fkey', 'similar_stacks', 'app_stacks', ['appstack_id'], ['id'])
    op.drop_constraint('sim_unique', 'similar_stacks', type_='unique')
    op.drop_column('similar_stacks', 'stack_id')
    op.drop_column('similar_stacks', 'similarity_value')
    op.drop_column('similar_stacks', 'similar_stack_id')
    op.drop_column('similar_stacks', 'analysis')
    op.create_table('app_stacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stack_json', postgresql.JSONB(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_stacks_pkey')
    )
    op.create_table('reference_stacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dependencies', postgresql.JSONB(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reference_stacks_pkey'),
    sa.UniqueConstraint('name', 'version', name='stack_unique')
    )
    op.drop_table('stacks')
    ### end Alembic commands ###
