#!/usr/bin/bash

RABBIT_HOST=${RABBITMQ_SERVICE_SERVICE_HOST:-coreapi-broker}
POSTGRES_HOST=${PGBOUNCER_SERVICE_HOST:-coreapi-pgbouncer}
ANITYA_HOST=${ANITYA_SERVICE_HOST:-anitya-server}

RABBIT_PORT=${RABBITMQ_SERVICE_SERVICE_PORT:-5672}
POSTGRES_PORT=${PGBOUNCER_SERVICE_PORT:-5432}
ANITYA_PORT=${ANITYA_SERVICE_PORT:-5000}

export F8A_CELERY_BROKER=amqp://guest@${RABBIT_HOST}:${RABBIT_PORT}
export F8A_POSTGRES=postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRESQL_DATABASE}
export F8A_ANITYA=http://${ANITYA_HOST}:${ANITYA_PORT}
