name: dependency-analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dependency-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          mkdir -p site-dir
          pip3 install --target=site-dir -r requirements.txt --upgrade
      - name: CodeReady Dependency Analysis
        uses: fabric8-analytics/gh-actions@main
        with:
          manifest-file-path: requirements.txt
          output-file-path: dependency-analysis-report.json
          pkg-installation-directory-path: site-dir
        env:
          CRDA_KEY: ${{ secrets.CRDA_KEY }}
